### ISSUE TITLE
Icons - licensing

### ISSUE THREAD

**Issue by adamajm** [GSA/ckanext-datagovtheme#105]
Hi team, what copyright license covers the [icons](https://github.com/GSA/ckanext-datagovtheme/tree/main/ckanext/datagovtheme/fanstatic_library/images) used in data.gov? Do these images go back to this archived [datagov-design repo](https://github.com/GSA/datagov-design)? I don't see all the icons used referenced there in the datagov-design repo.

Thinking specifically about options re: reusing some of them (WMS, CSV, ex) and/or contributing some ArcGIS specific icons... (Esri REST service). 

Best,
Adam

**Comment by nickumia-reisys** [comment]
Hi @adamajm Sorry for getting back to you so late.  I'm also relatively new to the data.gov team.  We don't actively monitor our extensions very well.  For future issues, I'd suggest adding an issue in our [main repo](https://github.com/GSA/datagov-deploy/issues).

Having queried the team, I've learned that most of our work (including your query about the icons) would fall under the [CC0 License](https://github.com/GSA/inventory-app/blob/main/LICENSE.md) which would help facilitate your plans.  Please let us know if there are any other concerns.
