### ISSUE TITLE
Error editing dataset on the data.gov theme

### ISSUE THREAD

**Issue by WaudoDavid** [GSA/ckanext-datagovtheme#209]
I have installed the theme but am an issue editing the dataset on the platform. This is the error 

**jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'pkg_dict'**

**Comment by btylerburton** [comment]
Hi @WaudoDavid not sure the root cause for your specific error but this extension might not function as expected outside the datagov catalog
